project:
  type: website
  output-dir: docs

website:
  title: "Dominik Schraff"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd