---
title: "CV"
format: html
---

## Academic Positions

-   **Since Nov. 2021**: Associate Professor, Department of Politics and Society, Aalborg University\
-   **2019–2021**: Senior Researcher, Center for International and Comparative Studies, ETH Zurich\
-   **2016–2019**: Postdoctoral Researcher, Center for International and Comparative Studies, ETH Zurich\
-   **2012–2016**: Graduate Assistant, Chair for Comparative Political Economy and Public Policy, University of St. Gallen\
-   **2009–2011**: Student Assistant, Chair for Political Science and International Comparative Social Research, University of Mannheim

## Education

-   **2013–2017**: University of St. Gallen, Doctorate in International Affairs and Political Economy\
-   **2011–2012**: University College London, MSc European Public Policy\
-   **2008–2011**: University of Mannheim, B.A. Political Science, Minor: Public Law

## Services to the Profession

-   Member of the editorial board at the *Journal of European Public Policy*\
-   Section chair “Political Behavior and Communication”, Danish Political Science Association\
-   Reviewer for many academic journals, see my [Web of Science Profile](https://www.webofscience.com) (only more recent activities recorded)

## Grants

-   **2022**: DPS Seed Grant, Aalborg University, 150,000 DKK (with Camilla Bjarnøe)\
-   **2021**: CIS Junior Scholar Research Grant & IPZ Inequality Grant, 15,000 CHF (with Lukas Haffert & Tabea Palmtag)\
-   **2019**: SNSF Ambizione Grant, 860,000 CHF

## Awards

-   **2023**: Award for best paper in 2022, *Journal of European Public Policy*\
-   **2021**: Best paper award, Arbeitskreis Europäische Integration e.V. (with Jana Lipps)\
-   **2020**: Fritz Thyssen Prize for best paper in the social sciences\
-   **2018**: ECSA Suisse best paper award\
-   **2017**: Rudolf Mäder Prize for best dissertation in political science and law, University of St. Gallen\
-   **2015**: Best Paper Award of the Council for European Studies Political Economy and Welfare Network (with Patrick Emmenegger and Paul Marx)\
-   **2013**: Dirk Berg-Schlosser Award for best poster presented at ECPR Summer School of Methods and Techniques, Ljubljana, 2nd prize (with Andre Walter)
