---
title: "Projects"
format: html
---

## Partner in EU Horizon project “Enhancing Democratic Support under Conditions of Geographic and Intersectional Inequalities in Europe (EDGE)”

**Budget:** 870’000 DKK  
**Period:** 2026–2029  
**Collaborators:** Alexia Katsanidou (PI) and Sofia Vasilopoulou (PI) + Consortium  
**Funding agency:** European Research Council

The EDGE project asks: ‘How are economic inequalities (objective and subjective) re-lated to European citizens’ democratic support?’. The overarching goals of EDGE are to: 1. systematically advance knowledge on how and under what conditions different types of economic ine-quality undermine or reinforce citizens’ democratic support, with a focus on the spatial (geographical) and intersectional dimensions of political resentment; 2. causally assess policy interventions related to objective and subjective inequalities in terms of their impact on democracy in order to propose efficient solutions for enhancing democratic support and resilience across diverse territorial contexts and social groups.

---

## Ambizione grant “Regional Inequality and the Political Geography of EU Support”

**Budget:** 860’000 CHF  
**Period:** 2019–2024  
**Collaborators:** Sven Hegewald  
**Funding agency:** Swiss National Science Foundation

This research project investigates the relationship between regional inequalities within Europe and citizens’ support for European integration. While previous research mainly focused on the role of vertical inequality (e.g., income inequality between individuals), this research project investigates how spatial inequalities (horizontal inequality) shape public support for the European Union (EU). In doing so, this project aims to contribute to a deeper understanding of the interrelationship between European integration, regional inequality, and societal preferences towards integration. Specifically, this project sheds new light on how space shapes public opinion about the EU, emphasizing the role of location for socialization and horizontal learning processes. This is a highly relevant endeavor as current challengers of European integration – such as Eurosceptic parties and secessionist movements – capitalize strongly on regional inequalities in Europe.

---

## Appealing to the good people

**Budget:** 150’000 DKK  
**Period:** 2023–2025  
**Collaborators:** Camilla Bjarnøe, Kristina Jessen Hansen, Mads Thau  
**Funding body:** Department of Politics and Society, Aalborg University (Seed Funding)

Parties tailor their communication in order to win public support. One way of doing so is by emphasizing valence qualities like the ability to perform or personal qualities like honesty and integrity. When communicating, parties can choose to appeal to one group rather than another or the public more broadly, yet little is known about which role valence plays compared to the established group appeals in the literature (policy-based and symbolic). We investigate this question relying on survey experiments including both in-group appeals to the working class and the upper-middle class conducted in the United States and Denmark.

---

## Appealing to the local voter

**Budget:** 15’000 CHF  
**Period:** 2021–2022  
**Collaborators:** Lukas Haffert, Tabea Palmtag  
**Funding body:** Center for Comparative and International Studies, ETH Zürich & IPZ Inequality Research Fund, University of Zürich

While it is increasingly well understood how citizens in urban and rural areas differ in their political preferences, we know much less about how these preferences are mobilized in the political system. Can place-based appeals be a potentially successful strategy for politicians? Does the mobilization of urban or rural voters mainly work through economic or cultural appeals? And which parties are seen as most likely to make such appeals?
